### ISSUE TITLE
Incorrect `mocha.run()` called with no tests

### ISSUE THREAD

**Issue by stoffeastrom** [shellscape/mocha-chrome#13]
* Operating System Mac OSX
* Node Version: 8.5.0
* NPM Version: 5.5.1
* mocha Version: 4.0.1
* mocha-chrome Version: 1.0.0

- [ ] This is a **feature** request
- [x] This is a **bug**

### Code

This [line](https://github.com/shellscape/mocha-chrome/blob/master/client/shim.js#L56) of code breaks this. Wouldn't it be better to check number of files?

### Expected Behavior
Be able to run tests using `requirejs`
### Actual Behavior
Errors out with `mocha.run()` called with no tests

Hi, cool library! I'm doing similar stuff as this library and wanted to try it using `requirejs`. I just hardcoded the `started` event to emit 1 and it worked :).

**Comment by shellscape** [comment]
Got a repo or gist that reproduces?

**Comment by stoffeastrom** [comment]
Not right now. I can look into that. It's a bit cumbersome since it's `requirejs`. Anyway I think the above doesn't make sense in that case since it's async. I'm calling `mocha.delay()` that adds a global `run` function that I later can call when all test files are required

**Comment by shellscape** [comment]
Depends on the version of Require.js being used, but we add the following to our test runner template:

```
  <script>
  require([], function () {
    mocha.run();
  });
  </script>
```

That queues `mocha.run` until Require is done doing it's thing, all modules are defined, and all requires are ready. `mocha.delay` is another option.

**Comment by stoffeastrom** [comment]
I just tried a minimal sample with a [gist](https://gist.github.com/stoffeastrom/ecee627fdfd06bf9f29eabf7bb76873e)

```shell
00:28 $ npx mocha-chrome https://rawgit.com/stoffeastrom/ecee627fdfd06bf9f29eabf7bb76873e/raw/c25c501676bbeb8a0c982340ab92807be0549264/index.html
function


  Test
    ✓ should work


  1 passing (19ms)
```
and it worked. I suspect it might have to do with the `mocha.delay` but needs more investigation. Anyway, a cool way to run a gist :)

**Comment by stoffeastrom** [comment]
So heres the repro

```shell
mocha-chrome https://rawgit.com/stoffeastrom/ecee627fdfd06bf9f29eabf7bb76873e/raw/13b56e2244fa0e3bb9bda5d9381f3fd755d1bb01/index.html
```
yields
```shell
Mocha-Chrome Failed: mocha.run() was called with no tests
```
If you get load timeout just run it again

**Comment by stoffeastrom** [comment]
I ran this locally and this seems to fix it for me

![screen shot 2017-10-25 at 11 28 32](https://user-images.githubusercontent.com/682243/31994558-58d14abc-b981-11e7-8812-60d1bda54d26.png)

**Comment by shellscape** [comment]
@stoffeastrom I'm having a really hard time following you. It's a best practice when reporting and discussing an issue to be clear and linear in your thoughts, as issue discussions are linear like a discussion forum. It's also a good practice not to post multiple successive posts, but rather edit your last post if there are no replies.

Your "repo" isn't a test repo; it's not even a suite of tests. It's an html file with no tests and just a `mocha.delay` call. So your issue seems to be claiming now that mocha saying there aren't any tests in incorrect, even though your test file contains no tests.

At this point I honestly have no idea what you're trying to report.

**Comment by stoffeastrom** [comment]
@shellscape Sorry for the confusing! As i linked before. This [gist](https://gist.github.com/stoffeastrom/ecee627fdfd06bf9f29eabf7bb76873e) indeed has a test file. Just clone it and you will see. Problem occurs when using `mocha.delay`. When the browser shim is emitting `started` there isn't any tests loaded yet and `mocha-chrome` errors out. If I change it to instead emit on runner start it works.

**Comment by shellscape** [comment]
Did you try what I posted in https://github.com/shellscape/mocha-chrome/issues/13#issuecomment-339139140 ? And if so, did it work?

**Comment by stoffeastrom** [comment]
Yes I tried only using the `mocha.run` and that works.

**Comment by shellscape** [comment]
OK so that's the route you'll want to go for testing with RequireJS.

Using the `m.runner` start event presents other concurrency issues that are problematic, which is why we didn't use that originally. That's based off of the same procedure that mocha-phantomjs-core uses, and that project dealt with the same concurrency issues in the past.

I'll also add a test using RequireJS to the test suite as a proof-of-concept for others on RequireJS moving forward.
