### ISSUE TITLE
feature request: override default chrome parameters

### ISSUE THREAD

**Issue by Spongman** [shellscape/mocha-chrome#28]
it would be great if you could override some of the default parameters that are passed to chrome.

currently we have to patch this npm package to remove the `--disable-gpu` flag, because we specifically want GPU support in our unit tests.

patching the package is a maintenance pain, it would be nice if we could just prevent that default.

**Comment by shellscape** [comment]
> Please note that this template is not optional. If you proceed with this form,
please fill out **_all_** fields, or your issue may be closed as "invalid."
Please do not delete this template. Please do remove this header to acknowledge this message.

Come on now, don't be lazy. When you see an issue template, especially one that says _"don't delete this template"_, you're supposed to fill it out. 

I'd recommend using one of the mocha + puppeteer modules that will probably suit your needs better.

**Comment by Spongman** [comment]
Are you closing this because I didn’t fill out your template? Or because you don’t think this is a valid issue?

**Comment by shellscape** [comment]
I closed it because:

- the template, warning, and the polite ask not to delete the template in the template header were ignored
- I don't think it's a good feature for this module
- there are other modules out there that will suit your needs better than this one, including any of the mocha + puppeteer modules (search NPM for those two terms, there are many)
